In [1]:
import pandas as pd
from pathlib import Path

**2.1 Load Dataset**

In [2]:
PROJECT_ROOT = Path().cwd().parent 
DATA_PATH = PROJECT_ROOT / 'data' / 'Raw'
application_train = pd.read_csv(DATA_PATH / 'application_train.csv')

**2.2 Dataset Overview**

In [3]:
print(f"Rows: {application_train.shape[0]:,}")
print(f"Columns: {application_train.shape[1]}")

Rows: 307,511
Columns: 122

In [4]:
application_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), str(16)
memory usage: 286.2 MB

In [5]:
application_train.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
count,307511.000000,307511.000000,307511.000000,3.075110e+05,3.075110e+05,307499.000000,3.072330e+05,307511.000000,307511.000000,307511.000000,...,307511.000000,307511.000000,307511.000000,307511.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000,265992.000000
mean,278180.518577,0.080729,0.417052,1.687979e+05,5.990260e+05,27108.573909,5.383962e+05,0.020868,-16036.995067,63815.045904,...,0.008130,0.000595,0.000507,0.000335,0.006402,0.007000,0.034362,0.267395,0.265474,1.899974
std,102790.175348,0.272419,0.722121,2.371231e+05,4.024908e+05,14493.737315,3.694465e+05,0.013831,4363.988632,141275.766519,...,0.089798,0.024387,0.022518,0.018299,0.083849,0.110757,0.204685,0.916002,0.794056,1.869295
min,100002.000000,0.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,0.000290,-25229.000000,-17912.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,189145.500000,0.000000,0.000000,1.125000e+05,2.700000e+05,16524.000000,2.385000e+05,0.010006,-19682.000000,-2760.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,278202.000000,0.000000,0.000000,1.471500e+05,5.135310e+05,24903.000000,4.500000e+05,0.018850,-15750.000000,-1213.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,367142.500000,0.000000,1.000000,2.025000e+05,8.086500e+05,34596.000000,6.795000e+05,0.028663,-12413.000000,-289.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000
max,456255.000000,1.000000,19.000000,1.170000e+08,4.050000e+06,258025.500000,4.050000e+06,0.072508,-7489.000000,365243.000000,...,1.000000,1.000000,1.000000,1.000000,4.000000,9.000000,8.000000,27.000000,261.000000,25.000000

In [6]:
application_train.describe(include = 'object')

/var/folders/qd/nb2xc8d94lv_f6q21wc98m5h0000gn/T/ipykernel_1339/923606878.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  application_train.describe(include = 'object')

,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,FONDKAPREMONT_MODE,HOUSETYPE_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE
count,307511,307511,307511,307511,306219,307511,307511,307511,307511,211120,307511,307511,97216,153214,151170,161756
unique,2,3,2,2,7,8,5,6,6,18,7,58,4,3,7,2
top,Cash loans,F,N,Y,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,Laborers,TUESDAY,Business Entity Type 3,reg oper account,block of flats,Panel,No
freq,278232,202448,202924,213312,248526,158774,218391,196432,272868,55186,53901,67992,73830,150503,66040,159428

**2.3 Missing Values Analysis**

In [7]:
missing = pd.DataFrame({
    'Missing Count' : application_train.isna().sum() , 
    'Missing Percent' : (application_train.isna().mean() * 100).round(2)
})

missing = missing.sort_values(
    by = 'Missing Percent' , 
    ascending= False
)

missing

                          Missing Count  Missing Percent
COMMONAREA_MEDI                  214865            69.87
COMMONAREA_AVG                   214865            69.87
COMMONAREA_MODE                  214865            69.87
NONLIVINGAPARTMENTS_MODE         213514            69.43
NONLIVINGAPARTMENTS_AVG          213514            69.43
...                                 ...              ...
NAME_FAMILY_STATUS                    0             0.00
NAME_EDUCATION_TYPE                   0             0.00
NAME_INCOME_TYPE                      0             0.00
AMT_ANNUITY                          12             0.00
SK_ID_CURR                            0             0.00

[122 rows x 2 columns]

In [44]:
extra_missing = missing[missing['Missing Percent'] > 50]
extra_missing

                          Missing Count  Missing Percent
COMMONAREA_MEDI                  214865            69.87
COMMONAREA_AVG                   214865            69.87
COMMONAREA_MODE                  214865            69.87
NONLIVINGAPARTMENTS_MODE         213514            69.43
NONLIVINGAPARTMENTS_AVG          213514            69.43
NONLIVINGAPARTMENTS_MEDI         213514            69.43
FONDKAPREMONT_MODE               210295            68.39
LIVINGAPARTMENTS_MODE            210199            68.35
LIVINGAPARTMENTS_AVG             210199            68.35
LIVINGAPARTMENTS_MEDI            210199            68.35
FLOORSMIN_AVG                    208642            67.85
FLOORSMIN_MODE                   208642            67.85
FLOORSMIN_MEDI                   208642            67.85
YEARS_BUILD_MEDI                 204488            66.50
YEARS_BUILD_MODE                 204488            66.50
YEARS_BUILD_AVG                  204488            66.50
OWN_CAR_AGE                      202929            65.99
LANDAREA_MEDI                    182590            59.38
LANDAREA_MODE                    182590            59.38
LANDAREA_AVG                     182590            59.38
BASEMENTAREA_MEDI                179943            58.52
BASEMENTAREA_AVG                 179943            58.52
BASEMENTAREA_MODE                179943            58.52
EXT_SOURCE_1                     173378            56.38
NONLIVINGAREA_MODE               169682            55.18
NONLIVINGAREA_AVG                169682            55.18
NONLIVINGAREA_MEDI               169682            55.18
ELEVATORS_MEDI                   163891            53.30
ELEVATORS_AVG                    163891            53.30
ELEVATORS_MODE                   163891            53.30
WALLSMATERIAL_MODE               156341            50.84
APARTMENTS_MEDI                  156061            50.75
APARTMENTS_AVG                   156061            50.75
APARTMENTS_MODE                  156061            50.75
ENTRANCES_MEDI                   154828            50.35
ENTRANCES_AVG                    154828            50.35
ENTRANCES_MODE                   154828            50.35
LIVINGAREA_AVG                   154350            50.19
LIVINGAREA_MODE                  154350            50.19
LIVINGAREA_MEDI                  154350            50.19
HOUSETYPE_MODE                   154297            50.18

**2.4 Duplicate Records**

In [9]:
application_train.duplicated().sum()

np.int64(0)

In [10]:
# there are no any duplicated values in dataset

**2.5 Data Types Validation**

In [11]:
application_train.dtypes.value_counts()

float64    65
int64      41
str        16
Name: count, dtype: int64

In [12]:
application_train.select_dtypes(include = 'number').shape

(307511, 106)

In [13]:
application_train.select_dtypes(include = 'object').shape

/var/folders/qd/nb2xc8d94lv_f6q21wc98m5h0000gn/T/ipykernel_1339/1759887725.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  application_train.select_dtypes(include = 'object').shape

(307511, 16)

**2.6 Unique Identifier Validation**

In [14]:
application_train['SK_ID_CURR'].is_unique

True

In [15]:
application_train['SK_ID_CURR'].duplicated().sum()

np.int64(0)

**2.7 Categorical Features**

In [16]:
for col in application_train.select_dtypes(include = 'object') :
    print(col , application_train[col].nunique())

NAME_CONTRACT_TYPE 2
CODE_GENDER 3
FLAG_OWN_CAR 2
FLAG_OWN_REALTY 2
NAME_TYPE_SUITE 7
NAME_INCOME_TYPE 8
NAME_EDUCATION_TYPE 5
NAME_FAMILY_STATUS 6
NAME_HOUSING_TYPE 6
OCCUPATION_TYPE 18
WEEKDAY_APPR_PROCESS_START 7
ORGANIZATION_TYPE 58
FONDKAPREMONT_MODE 4
HOUSETYPE_MODE 3
WALLSMATERIAL_MODE 7
EMERGENCYSTATE_MODE 2

/var/folders/qd/nb2xc8d94lv_f6q21wc98m5h0000gn/T/ipykernel_1339/1242185089.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in application_train.select_dtypes(include = 'object') :

In [29]:
categorical_features = len(application_train.select_dtypes(include = 'object'))
categorical_features

/var/folders/qd/nb2xc8d94lv_f6q21wc98m5h0000gn/T/ipykernel_1339/3916179915.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = len(application_train.select_dtypes(include = 'object'))

307511

**2.8 Numerical Features**

In [24]:
numeric_features = len(application_train.select_dtypes(include= 'number').columns)
numeric_features

106

In [20]:
application_train.select_dtypes(include='number').describe().T

,count,mean,std,min,25%,50%,75%,max
SK_ID_CURR,307511.0,278180.518577,102790.175348,100002.0,189145.5,278202.0,367142.5,456255.0
TARGET,307511.0,0.080729,0.272419,0.0,0.0,0.0,0.0,1.0
CNT_CHILDREN,307511.0,0.417052,0.722121,0.0,0.0,0.0,1.0,19.0
AMT_INCOME_TOTAL,307511.0,168797.919297,237123.146279,25650.0,112500.0,147150.0,202500.0,117000000.0
AMT_CREDIT,307511.0,599025.999706,402490.776996,45000.0,270000.0,513531.0,808650.0,4050000.0
...,...,...,...,...,...,...,...,...
AMT_REQ_CREDIT_BUREAU_DAY,265992.0,0.007000,0.110757,0.0,0.0,0.0,0.0,9.0
AMT_REQ_CREDIT_BUREAU_WEEK,265992.0,0.034362,0.204685,0.0,0.0,0.0,0.0,8.0
AMT_REQ_CREDIT_BUREAU_MON,265992.0,0.267395,0.916002,0.0,0.0,0.0,0.0,27.0
AMT_REQ_CREDIT_BUREAU_QRT,265992.0,0.265474,0.794056,0.0,0.0,0.0,0.0,261.0
AMT_REQ_CREDIT_BUREAU_YEAR,265992.0,1.899974,1.869295,0.0,0.0,1.0,3.0,25.0

**2.9 Constant Features**

In [47]:
constant_columns = []
for col in application_train.columns :
    if application_train[col].nunique() == 1:
        constant_columns.append(col)
constant_columns

[]

**2.10 Data Quality Summary**

In [48]:
print(f"Rows: {application_train.shape[0]:,}")
print(f"Columns: {application_train.shape[1]}")
print(f'Duplicated Rows : {application_train.duplicated().sum()}')
print(f'number of numeric features : {numeric_features}')
print(f'number of categorical featues : {categorical_features}')
print(f'columns who have missing values : \n{missing.index}\n and len of them is : {len(missing.index)}')
print(f'columns who have more than 50% missing values : {extra_missing} \nand number of then is : {len(extra_missing)}')
print(f'number of constant features are : {len(constant_columns)}')

Rows: 307,511
Columns: 122
Duplicated Rows : 0
number of numeric features : 106
number of categorical featues : 307511
columns who have missing values :
Index(['COMMONAREA_MEDI', 'COMMONAREA_AVG', 'COMMONAREA_MODE',
       'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAPARTMENTS_AVG',
       'NONLIVINGAPARTMENTS_MEDI', 'FONDKAPREMONT_MODE',
       'LIVINGAPARTMENTS_MODE', 'LIVINGAPARTMENTS_AVG',
       'LIVINGAPARTMENTS_MEDI',
       ...
       'DAYS_REGISTRATION', 'DAYS_EMPLOYED', 'DAYS_BIRTH',
       'REGION_POPULATION_RELATIVE', 'NAME_HOUSING_TYPE', 'NAME_FAMILY_STATUS',
       'NAME_EDUCATION_TYPE', 'NAME_INCOME_TYPE', 'AMT_ANNUITY', 'SK_ID_CURR'],
      dtype='str', length=122)
 and len of them is : 122
columns who have more than 50% missing values :                           Missing Count  Missing Percent
COMMONAREA_MEDI                  214865            69.87
COMMONAREA_AVG                   214865            69.87
COMMONAREA_MODE                  214865            69.87
NONLIVINGAPARTMENTS_MODE         213514            69.43
NONLIVINGAPARTMENTS_AVG          213514            69.43
NONLIVINGAPARTMENTS_MEDI         213514            69.43
FONDKAPREMONT_MODE               210295            68.39
LIVINGAPARTMENTS_MODE            210199            68.35
LIVINGAPARTMENTS_AVG             210199            68.35
LIVINGAPARTMENTS_MEDI            210199            68.35
FLOORSMIN_AVG                    208642            67.85
FLOORSMIN_MODE                   208642            67.85
FLOORSMIN_MEDI                   208642            67.85
YEARS_BUILD_MEDI                 204488            66.50
YEARS_BUILD_MODE                 204488            66.50
YEARS_BUILD_AVG                  204488            66.50
OWN_CAR_AGE                      202929            65.99
LANDAREA_MEDI                    182590            59.38
LANDAREA_MODE                    182590            59.38
LANDAREA_AVG                     182590            59.38
BASEMENTAREA_MEDI                179943            58.52
BASEMENTAREA_AVG                 179943            58.52
BASEMENTAREA_MODE                179943            58.52
EXT_SOURCE_1                     173378            56.38
NONLIVINGAREA_MODE               169682            55.18
NONLIVINGAREA_AVG                169682            55.18
NONLIVINGAREA_MEDI               169682            55.18
ELEVATORS_MEDI                   163891            53.30
ELEVATORS_AVG                    163891            53.30
ELEVATORS_MODE                   163891            53.30
WALLSMATERIAL_MODE               156341            50.84
APARTMENTS_MEDI                  156061            50.75
APARTMENTS_AVG                   156061            50.75
APARTMENTS_MODE                  156061            50.75
ENTRANCES_MEDI                   154828            50.35
ENTRANCES_AVG                    154828            50.35
ENTRANCES_MODE                   154828            50.35
LIVINGAREA_AVG                   154350            50.19
LIVINGAREA_MODE                  154350            50.19
LIVINGAREA_MEDI                  154350            50.19
HOUSETYPE_MODE                   154297            50.18
and number of then is : 41
number of constant features are : 0